### PR TITLE
Update 2020.1

### PR DESCRIPTION
**Pull request by bnavigator**

### CODE REVIEW

**Comment by bnavigator** [comment]
Oops!
I meant to test on github workflow first. Similar to https://github.com/macgpg/libmacgpg-free/pull/9

Anyway, keeping this open, maybe it will be useful eventually.

**Comment by jpr5** [comment]
My sense of the original author's recent comments (from when the most recent GPG release came out) is that they're essentially done with this project and have no interest in working on it further.  

Unless @GpgMailNoActivation decides to give folks commit rights, It might make more sense to just anoint another repo as authoritative, and do work there.  FWIW, my $0.02.

**Comment by jpr5** [comment]
But really do appreciate you spending time on this.  I'm sure tons of folks will be grateful.

**Comment by bnavigator** [comment]
Please checkout https://github.com/bnavigator/GpgMailNoActivation/tree/update-2020.1, I have set up another Github workflow, but unfortunately the linker fails due to the lack of the mail.app. So someone with a real Mac should check it.

```
6964 ld: warning: directory not found for option '-F/Users/runner/runners/2.263.0/work/GpgMailNoActivation/GpgMailNoActivation/Source/GPGMail_3/Dependencies/Libmacgpg/build/Release'
6965 ld: warning: directory not found for option '-F/Users/runner/Library/Containers/com.apple.mail/Data/Library/Frameworks'
6966 ld: warning: directory not found for option '-F/Users/runner/Library/Frameworks'
6967 ld: file not found: /Applications/Mail.app/Contents/MacOS/Mail
6968 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I understood https://github.com/GpgMailNoActivation/GpgMailNoActivation/issues/4#issuecomment-579065249 so that @GpgMailNoActivation is still willing to accept PRs. As mentioned, I do not even own a Mac. Thus, I am certainly not in the position of maintaining an new authoritative repo. Maybe the maintainer of libmacgpg-free @jonasschnelli is willing to help?

**Comment by jpr5** [comment]
I'm on a Mac.  Where's a link to the workflow?  vs. me asking if you're following the build instructions and asking about what you may/may not be doing differently.

**Comment by bnavigator** [comment]
https://github.com/bnavigator/GpgMailNoActivation/blob/master/.github/workflows/make.yml

https://github.com/bnavigator/GpgMailNoActivation/runs/786161471?check_suite_focus=true

Is there a command to add which maybe installs the necessary mail.app framework?

**Comment by jpr5** [comment]
Ahh, you had it on master, not your branch.  OK playing with it now.

**Comment by bnavigator** [comment]
Yes I wanted to keep that separate from the PR. Good luck with it, I am off to bed for today. :)

**Comment by jpr5** [comment]
@bnavigator Get you a PR on your repo for the build fix.  Latest MacOS moves most system software under `/System`, with special file system protections to prevent malware/modification.  

Basically ran: 

```
git grep -zl 'Applications/Mail'| xargs -0 sed -i "" -e 's/Applications\/Mail/System\/Applications\/Mail/' 
git checkout -f Source/GPGMail*/Docs
git commit -a ...
```

**Comment by jpr5** [comment]
Current state of it is that it builds cleanly, but won't load.  I tried [opichal's Info.plist addition](https://github.com/GpgMailNoActivation/GpgMailNoActivation/pull/6/commits/9bcfa5d2495304cee97d5041fcaa6eddcbaaae57) thinking it might be that simple, but that also doesn't make it work.

There has to be some other missing change that tells `Mail.app` it's looking at a compatible plugin...

**Comment by jpr5** [comment]
I lied, it works!  :-D 

Apparently you need to wipe out the build directory in order for modifications to `Resources/Info.plist` to get picked up.

Merge in my PR to your tree, then I think yours will automatically update here.

**Comment by MKesenheimer** [comment]
I can confirm! The newest version from branch update-2020.1 (bnavigator/GpgMailNoActivation) works for me. Thank you so much for your time and effort!

**Comment by StevenM1** [comment]
I can also confirm it works - thanks a lot!

**Comment by sadyhr** [comment]
Sorry for my really noob-behaviour ,()
Precisely where and how do I find and compile a version for macOS 10.13 of this version of the plugin? And it's just the Mail-plugin for the GPG Suite v4 I shall compile—all the other parts are still to be found at the original gpgtools site, right?

**Comment by bnavigator** [comment]
Should the plist in GPGMail_3 also be updated or is this version strictly non-Catalina?

**Comment by bnavigator** [comment]
Compiled mailbundles can be found here
https://github.com/bnavigator/GpgMailNoActivation/releases/tag/Ver_2020.1_rc

**Comment by sadyhr** [comment]
> Compiled mailbundles can be found here
> https://github.com/bnavigator/GpgMailNoActivation/releases/tag/Ver_2020.1_rc

Thanx a lot ,-)

**Comment by bnavigator** [comment]
Thanks for the positive feedback. Is the activation dialog completely gone as the app now thinks it has a valid plan or is there sill some invalid information displayed, e.g. a wrong expiry date?

I removed the source and binary packages from the repository itself. They should be assets in the releases. The custom replacement dmg is still missing. I do not know how to create that. Maybe another Github action could take care of it?

**Comment by StevenM1** [comment]
For me the activation dialog appears to be completely gone (although I must add that, using the official GPGmail plugin, the activation dialog also didn't appear on every boot but only once in a while so perhaps it comes back?).

Sorry, my coding knowledge is limited to Python/R so can't help with creating the dmg :-(

**Comment by sadyhr** [comment]
> Compiled mailbundles can be found here
> https://github.com/bnavigator/GpgMailNoActivation/releases/tag/Ver_2020.1_rc

Thanx a lot - I followed the guide after installer the whole tools on macOS 10.13.
I had to reboot the Mac, before any encryption worked.

GPG Mail plugin DOES ask if I will register or start trial. after clicking trial, it displays »Registered to [null]« and »code [null]« and works like a charm.

Thank you very much for you help and work.

**Comment by MKesenheimer** [comment]
Could you please note in the readme: In order to get this running correctly, you have to deactivate the conflicting plugin `GPGMailLoader.mailbundle` in the Mail plugin manager.
For me, Mail crashed every time if tried to send an encrypted email. Did someone else observe this behaviour?

**Comment by bnavigator** [comment]
> Could you please note in the readme: In order to get this running correctly, you have to deactivate the conflicting plugin `GPGMailLoader.mailbundle` in the Mail plugin manager.
> For me, Mail crashed every time if tried to send an encrypted email. Did someone else observe this behaviour?

Interesting. Where does the GPGMailLoader.mailbundle come from? I don't see it in the original sources.

**Comment by MKesenheimer** [comment]
> > Could you please note in the readme: In order to get this running correctly, you have to deactivate the conflicting plugin `GPGMailLoader.mailbundle` in the Mail plugin manager.
> > For me, Mail crashed every time if tried to send an encrypted email. Did someone else observe this behaviour?
> 
> Interesting. Where does the GPGMailLoader.mailbundle come from? I don't see it in the original sources.

The `GPGMailLoader.mailbundle` comes directly from the official installer (https://gpgtools.org)

**Comment by bnavigator** [comment]
What does it do?

**Comment by chiffon-rouge** [comment]
I had the "GPGMailLoader.mailbundle" unchecked in my under "Plugins" in Mail. It vanished as soon as I activated the new plugin this repository provided. Right now I'm not sure it worked for. In the Mail preferences it seems like it did [1], but in the entry under "system preferences" it's still listed as a trail version [2]. I guess I'll see in 30 days. So far, thanks to bnavigator and everyone involved for tackling this issue.

[1]
Bildschirmfoto 2020-06-19 um 14 31 50

[2]
Bildschirmfoto 2020-06-19 um 14 32 21

**Comment by MKesenheimer** [comment]
> What does it do?

I thought it is the original mail PGP plugin, but I am not sure.

@chiffon-rouge: I'm using PGPMail way longer than 30 days and I am able to send and receive encrypted emails.

**Comment by chiffon-rouge** [comment]
> @chiffon-rouge: I'm using PGPMail way longer than 30 days and I am able to send and receive encrypted emails.

Alright. I was just wondering if this is supposed to look like it does on my system when the plugin is working or if the reference to the trial version (with the countdown of the days) is an indicator that it doesn't.

**Comment by jrschat** [comment]
I must have done something wrong.

image

I installed the new version using the installer from assets, copied over the files to library manually, restarted, and am now only have email decryption.

**Comment by jpr5** [comment]
What's `Mail.app` Preferences / General / Manage Plugins say?

**Comment by jrschat** [comment]
I am still on High Sierra so it gets its own tab in preferences.

image

**Comment by jpr5** [comment]
Well, seeing the Build # makes me think that the right code is in place.  I don't know much about GPGTools' internal workings in particular, but I will say that I've seen open-source/cmdline GPG do something similar when something is wrong with the private key(s), i.e. it's missing, or has bad filesystem permissions, or something like that.  The plugin itself will not work at all when not activated || not using this hack, so that it works at all suggests the decrypt-only cause lies elsewhere.

**Comment by sadyhr** [comment]
> I am still on High Sierra so it gets its own tab in preferences.
> 
> image

I'm on 10.13 too and get the following:

billede

And everything is working fine.

I installede the official package, took the plugin out from within /Library/Mail/Bundles/
and NOT the ~/Library/Mail/Bundles/ as suggested, since it was not there, and then replaced with the plugin from this project.

**Comment by jrschat** [comment]
Hmm, I put them /Library/Application Support/GPGTools/GPGMail because that was where the installer put them.

I have downgrade a version till I have time to mess with it more as I suspect something is wrong on my machine.  If I try to build the plugin myself, it fails.  I will have to mess with it when I have more time.

**Comment by jpr5** [comment]
I suspect you can’t build it because my change basically moves the hard-coded Mail.app path from /Applications/Mail.app (Everything before Catalina) to /System/Applications/Mail.app (Catalina+).  I honestly don’t know if this affects the runtime dependencies vs buildtime; hearing that it works for others on non-Catalina makes me think not.  

If it does, then we’d need to adjust the build system to alter the path based on what version of macOS was being built on.  Shrug, if there’s more complaints, it can be done..

**Comment by watou** [comment]
> For me, Mail crashed every time if tried to send an encrypted email. Did someone else observe this behaviour?

@MKesenheimer I am on Mojave and I had checked both `GPGMail_3.mailbundle` and `GPGMail_4.mailbundle` and Mail.app was crashing on signing.  After only checking the `GPGMail_4.mailbundle`, signing and encrypting both appear to be working now.

**Comment by bnavigator** [comment]
> I am still on High Sierra so it gets its own tab in preferences.
> 
> image

What happens if you click on activate?

**Comment by watou** [comment]
@bnavigator On my Mojave setup, I was never asked to activate.  This is my GPG Mail tab:

tab

**Comment by bnavigator** [comment]
I have not completely analyzed the code, but I suspect the saved state at time of the replacemant makes a difference:

- Freshly installed, no Trial started (= no active Support Plan)
- Active "Trial" Support Plan
- Trial or formerly payed Support Plan expired

Most of the logic we have to deal with is in [GMSupportPlan.m](https://github.com/bnavigator/GpgMailNoActivation/blob/update-2020.1/Source/GPGMail_4/Dependencies/GMSupportPlan/GMSupportPlan.m) and [GMSupportPlanManager.m](https://github.com/bnavigator/GpgMailNoActivation/blob/update-2020.1/Source/GPGMail_4/Dependencies/GMSupportPlan/GMSupportPlanManager.m)

**Comment by StevenM1** [comment]
> Could you please note in the readme: In order to get this running correctly, you have to deactivate the conflicting plugin `GPGMailLoader.mailbundle` in the Mail plugin manager.
> For me, Mail crashed every time if tried to send an encrypted email. Did someone else observe this behaviour?

Heh, I only realize now that this is also the case for me. That is, upon first start of Mail, the GPGMailLoader_2.mailbundle is loaded, as well as the GPGMail_4.mailbundle from this repository. When I try to send an encrypted email, it indeed crashes. When I then uncheck GPGMailLoader_2.mailbundle and restart Mail.app, I can send encrypted emails without Mail crashing. However, interestingly, even though I unchecked GPGMailLoader_2.mailbundle before restarting, it is again automatically checked after the restart of Mail (but without causing any crashes).

Another mail restart (without unchecking GPGMailLoader_2) leads to crashes again.

Screenshot 2020-06-20 at 14 02 45

**Comment by jrschat** [comment]
> > I am still on High Sierra so it gets its own tab in preferences.
> > image
> 
> What happens if you click on activate?

I apologize, I missed your question.  Bounces me back down to GPG Mail Version 3.2.2 and stays in decrypt only mode.

**Comment by bnavigator** [comment]
@jrschat, did you try to follow the new installation instructions and delete GPGMailLoader.mailbundle?

**Comment by jrschat** [comment]
@bnavigator, now I did.  It shows null null now.  System Preferences shows 22 days of trial remaining.  I'll update you if after the time passes it actually stops working.

**Comment by bnavigator** [comment]
I made a new release. The Build number now gets updated, so there is one more check that you use the right bundle.

https://github.com/bnavigator/Free-GPGMail/releases/tag/v2020.1

**Comment by fessyfoo** [comment]
that worked for me.   thank you.   it's hard to get talk people into using GPG when there's not an easy to use free option out there.

**Comment by jrschat** [comment]
Well for some reason if I try and sign and email, mail crashes but they will send unsigned and encrypted unsigned just fine.  Very strange.

**Comment by fuvidani** [comment]
Hi, 
first of all thank you for your efforts and releasing this plugin. I'm having difficulties getting rid of the decrypt only mode following the installation guide. I'm on Mojave (10.14.6) and trying to do a clean, fresh install (= neither previous nor currently started trial). In my case, after installing the GPG Suite there are bundles created in both `/Library/Mail/Bundles` and `/Library/Application Support/GPGTools/GPGMail`(please refer to the screenshots below). 

Contents of `/Library/Mail/Bundles`
Library_Bundles

Contents of `/Library/Application Support/GPGTools/GPGMail`
Library_App_Support_GPGTools

I've already done 3 installation&deinstallation rounds (with reboots in-between) each time with a different interpretation of your guide: 
- (a) delete `GPGMailLoader.mailbundle` folder inside `/Library/Mail/Bundles` and placing `Free-GPGMail_4.mailbundle` into it 
- (b) replace `GPGMail_4.mailbundle` inside `/Library/Application Support/GPGTools/GPGMail` with `Free-GPGMail_4.mailbundle`
- (c) combination of the above both

Unfortunately, the decrypt only mode doesn't want to disappear no matter what I do. Interestingly though, when following the (a) path, the build number shows `180045.46` which should verify the correct installation according to your guide. I feel clueless now; I've read through this thread but nothing seems to help. Do you have any tips for me? Could the fact that my system is still on Mojave and not Catalina be the cause of the problem? Any help would be much appreciated.

**Comment by bnavigator** [comment]
Delete ALL the old GPGMail Mailbundles. Chances are that the wrong version is still picked up for some library call. Try Free-GPGMail_3 and Free-GPGMail_4 individually (only one installed at the time)

**Comment by fuvidani** [comment]
Thanks @bnavigator for the response, but still no luck here. I've completely uninstalled the suite, even did a system reboot. After the new suite installation, following your advice I deleted everything from both `/Library/Mail/Bundles` and `/Library/Application Support/GPGTools/GPGMail` without even opening the Mail app and only used one of the Free-GPGMail_* files at a time for each attempt. Switching between version 3 and 4 doesn't help either, I'm stuck at decrypt only mode on both versions. I've noticed though, that in the course of repeated installations I only got the welcome to GPGTools screen only once yesterday, indicating that they likely store this information in a preferences file somewhere which doesn't get deleted during uninstallation. Maybe that causes the problem, I don't know... Just trying to make sense out of this....

Version

**Comment by bnavigator** [comment]
Did you try to click the `Activate` button? That should also trigger a code path which is short-circuited in Free-GPGMail

**Comment by bnavigator** [comment]
> indicating that they likely store this information in a preferences file somewhere which doesn't get deleted during uninstallation

The fact that you are in `Decrypt Only Mode` immediately without the trial period also indicates such a stored state.

**Comment by fuvidani** [comment]
> Did you try to click the `Activate` button? That should also trigger a code path which is short-circuited in Free-GPGMail

Yes I do so every time and I'm prompted the e-mail and activation code plus I could start the 30 days trial (which I haven't done yet assuming it to be an unnecessary step).

**Comment by jrschat** [comment]
Do you have alias files in /Library/Application Support/GPGTools/GPGMail? I had to rename Free-GMGMail_4.mailbundle to GMGMail_4.mailbundle.

**Comment by fuvidani** [comment]
> Do you have alias files in /Library/Application Support/GPGTools/GPGMail? I had to rename Free-GMGMail_4.mailbundle to GMGMail_4.mailbundle.
> […](#)
> On 18-Sep-2020, at 10:20, Daniel Füvesi ***@***.***> wrote: Did you try to click the Activate button? That should also trigger a code path which is short-circuited in Free-GPGMail Yes I do so every time and I'm prompted the e-mail and activation code plus I could start the 30 days trial (which I haven't done yet assuming it to be an unnecessary step). — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I pasted a screenshot of the folder contents after a clean installation, here it is again:
GPGMail
As you can see via the tiny arrows, the `GPGMail_13.mailbundle` and `GPGMail_14.mailbundle` are actually aliases. However, I've deleted all of the 4 files after installation as suggested by bnavigator. Now that you mentioned this, I went ahead and pasted the modified bundle with the name GPGMail_4.mailbundle, but nothing changed. 

How was it in your case, @jrschat? Did you have to only touch the contents of `/Library/Application Support/GPGTools/GPGMail`? It seems to me that people here make the overwrites **either** inside `/Library/Mail/Bundles` **or** `/Library/Application Support/GPGTools/GPGMail`, but not both. I'm puzzled by the fact that I automatically get bundles in both locations after installing the suite.

**Comment by jrschat** [comment]
I had lots of attempts trying to get it to work, I have GPGMail_4.mailbundle in both locations. I also have the aliases (they point at the bundle).

**Comment by fuvidani** [comment]
I finally managed to get it work thanks to this comment:
> GPG Mail plugin DOES ask if I will register or start trial. after clicking trial, it displays »Registered to [null]« and »code [null]« and works like a charm.

So in my case, I didn't even start the trial before assuming that the modified plugin would make it void anyway if it were installed correctly. Nevertheless, I clicked on `Activate` followed by `Start Trial`. It told me that it would downgrade me from version 4 to version 3, I clicked ok. Mail restarted automatically, version stayed at 4.1 and now I also have the support plan filled with `null` values.

Thank you @bnavigator and @jrschat for the support. For those who might be eagerly waiting for Big Sur, quick heads-up that [GPG Mail is incompatible with it](https://gpgtools.tenderapp.com/discussions/feedback/16109-gpg-mail-big-sur-support) for the moment.

**Pull request closed without merging**
