### PR TITLE
Add Catalina support (10.15.5)

### PR DESCRIPTION
**Pull request by opichals**
Works for me with Mail.app 13.4

### CODE REVIEW

**Comment by MKesenheimer** [comment]
Do I have to build from source or can I use your prebuilt versions? 
For me there is no folder
`/Library/Application\ Support/GPGTools/GPGMail/`
after installing GPGTools from Downloads/GPG_Suite-2019.1_83.dmg.

**Comment by opichals** [comment]
I used `GPG_Suite-2020.1.dmg`, dropped the `/Library/Mail/Bundles/GPGMailLoader*.mailbundle` to uninstall the GPGMail.

Then installed a from-source build created using `xcodebuild  -config Release -scheme GMailinator build` into `~/Library/Mail/Bundles/` (although I assume you could replace it in the system-wide `/Library/Mail/Bundles` folder as well).

**Comment by jpr5** [comment]
So... it's not clear, does this actually work or not?  Has anyone other that opichals been able to reproduce it?

**Comment by MKesenheimer** [comment]
No, sorry, I could not verify this. Although I managed to build all sources opichal mentioned. 

There were some problems in the end, for example, I did not find a build of GPG_Mail4 after successfully building the sources. 

So, I am not exactly sure what the steps are to completely and successfully get this working.

**Pull request closed without merging**
